// schema.ts
// GENERATED BY GITHUB COPILOT
// DO NOT EDIT
export const QuizSetSchema = {
  type: "object",
  properties: {
    singleChoice: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question: { type: "string" },
          options: {
            type: "array",
            items: {
              type: "object",
              properties: {
                id: { type: "number" },
                content: { type: "string" },
              },
              required: ["id", "content"],
            },
          },
          answer: { type: "number" },
          explanation: { type: "string" },
        },
        required: ["question", "options", "answer"],
      },
    },
    multipleChoice: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question: { type: "string" },
          options: {
            type: "array",
            items: {
              type: "object",
              properties: {
                id: { type: "number" },
                content: { type: "string" },
              },
              required: ["id", "content"],
            },
          },
          answer: {
            type: "array",
            items: { type: "number" },
          },
          explanation: { type: "string" },
        },
        required: ["question", "options", "answer"],
      },
    },
    judgement: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question: { type: "string" },
          answer: { type: "boolean" },
          explanation: { type: "string" },
        },
        required: ["question", "answer"],
      },
    },
  },
  additionalProperties: false,
};
